Neos:
  Neos:
    fusion:
      autoInclude:
        NeosRulez.NodeSearch: true
    userInterface:
      translation:
        autoInclude:
          NeosRulez.NodeSearch:
            - Main
            - 'NodeTypes/*'
            - 'NodeTypes/Content/*'
            - 'NodeTypes/Component/*'
    nodeTypes:
      groups:
        neosrulezNodeSearch:
          position: 'end'
          label: NeosRulez.NodeSearch:Main:neosrulezNodeSearch
#NeosRulez:
#  NodeSearch:
#    ignoredNodetypes:
#      values:
#        - 'Acme.Package:Document.Category'
#        - 'Acme.Site:Document.404'
